#!/usr/bin/env bash
# Script Bash que configura una nueva máquina Ubuntu para
# respetar los requisitos anteriores
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart 