#!/usr/bin/env bash
# Script Bash que configura una nueva máquina Ubuntu para
# respetar los requisitos anteriores
apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start 