#!/usr/bin/env bash
# Bash Script to configure an NGINX server with a custom HTTP header
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" |sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i " /listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\n\tinternal;\n}\n' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By \$hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
