#!/usr/bin/env bash
# Script that starts nginx as nginx user
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "1 i user nginx;" /etc/nginx/nginx.conf
sudo -u nginx service nginx restart